#!/usr/bin/env python
import os
import sys
import httplib
import libsinan.args
import libsinan.sinexceptions
import socket
import time

CONNECTION_REFUSED = 111

def start_server(largs):
    """ Start the server. Use the 'server_command' local
    opt if it exists, otherwise just use 'sinserv' on the path """
    cmd = "sinserv"
    prefix = ""
    try:
        cmd = largs['special_opts']['server_command']
    except KeyError:
        pass
    try:
        prefix = largs['special_opts']['prefix']
        prefix += "/bin/"
    except KeyError:
        pass
    if os.system(prefix + cmd) != 0:
        raise libsinan.sinexceptions.SinanError("Unable to start " + cmd)
    print "starting server, waiting for 2 seconds to let it start up"
    time.sleep(2)



def initiate_task(largs):
    """ Trys to open a connection. If the connection fails
    due to a connection refused we probably just need to start
    sinan. Look for a sinserve either in a passed in path
    or in the default path"""
    task = largs['task']
    handler = libsinan.get_handler_for_task(task)
    try:
        handler.handle(largs)
    except (socket.error), e:
        code, reason = e
        if code == CONNECTION_REFUSED:
            start_server(largs)
            handler.handle(largs)
        else:
            print "Unable to build got : "
            print e


def print_help():
    print """ sinan [args] [task]
local args (+) and server args. local args may be any of the following
    +url  :  The url to connect to and control
    +help :  This help message

Server args are much more complex. There are always sane defaults so
you shouldn't need them, but you may. To get information about server
args read the sinan documentation.
"""

def main(argv=None):
    if argv is None:
        argv = sys.argv[1:]

    largs = libsinan.args.parse(argv, "build",
                                {'url' : 'localhost:8599'})
    try:
        if largs['special_opts']['help']:
            print_help()
            return 2
    except KeyError:
        pass
    try:
        initiate_task(largs)
    except libsinan.sinexceptions.SinanError, e:
        print e.value
    except KeyboardInterrupt:
        print "\n\nexiting at user request. Thanks!"


if __name__ == "__main__":
    sys.exit(main())

