#! /bin/sh
erl -pa /usr/local/erlware/application_packages/5.6.3/lib/sgte-0.7.1/ebin \
  -pa _build/development/apps/etask-0.5.0/ebin  -pa \
 _build/development/apps/sinan-0.10.0.13/ebin -pa \
 _build/development/apps/sinan_web_api-0.1.0.4/ebin \
 -pa ../fconf/_build/development/apps/fconf-0.3.0.0/ebin \
 -pa ../ktuo/_build/development/apps/ktuo-0.4.0.1/ebin \
  -pa ../crary/_build/development/apps/crary-0.2.3/ebin \
 -pa /usr/local/erlware/application_packages/5.6.3/lib/eunit-2.0/ebin\
  -pa /usr/local/erlware/application_packages/5.6.3/lib/ibrowse-1.4/ebin\
 -pa ../erlware/_build/development/apps/cryptographic-0.2.0/ebin -pa \
 ../erlware/_build/development/apps/ewlib-0.7.4.0/ebin -pa \
 ../erlware/_build/development/apps/ewrepo-0.16.6.1/ebin -pa \
 ../uri/_build/development/apps/uri-0.1.0/ebin -pa \
 ../erlware/_build/development/apps/gas-5.1.0/ebin -pa\
 /usr/local/erlware/application_packages/5.6.3/lib/gtime-0.9.4/ebin\

