#!/bin/sh

PROG=$$0
PROG_DIR=$$(cd `dirname $$0`; pwd)
test -h $$0 && PROG=$$(readlink $$0)
export ROOTDIR=$$(dirname $$PROG_DIR)

#### Fill in values for these variables ####
REL_NAME=$project_name$
REL_VSN=$project_version$
ERTS_VSN=$erts_version$
INVOCATION_SUFFIX="-prefix $$ROOTDIR"
###########################################

$$ROOTDIR/bin/erlware_release_start_helper $$REL_NAME $$REL_VSN $$ERTS_VSN sys.config $$INVOCATION_SUFFIX
